"""empty message

Revision ID: 71b2192ebebc
Revises: 9b563b48550a
Create Date: 2017-11-01 16:59:59.153000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b2192ebebc'
down_revision = '9b563b48550a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippets', sa.Column('update_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_snippets_update_timestamp'), 'snippets', ['update_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snippets_update_timestamp'), table_name='snippets')
    op.drop_column('snippets', 'update_timestamp')
    # ### end Alembic commands ###
